In [1]:
# 1. Импортировать NumPy под именем np
import numpy as np

In [2]:
# 2. Напечатать версию и конфигурацию
print(np.__version__)

1.24.3


In [3]:
# 3. Создать вектор (одномерный массив) размера 10, заполненный нулями
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# 4. Создать вектор размера 10, заполненный единицами
a=np.array([])
i=0
while i<10:
    a=np.append(a,1)
    i+=1
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [5]:
# 5. Создать вектор размера 10, заполненный числом 2.5
print(np.full(10,2.5))

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


In [6]:
# 6. Как получить документацию о функции numpy.add из командной строки?
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [7]:
# 7. Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1
a=np.array([])
i=0
while i<10:
    if i==4:
        i+=1
        a=np.append(a,1)
        continue
    a=np.append(a,0)
    i+=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
# 8. Создать вектор со значениями от 10 до 49
a=np.array([])
s=10
while s!=50:
    a=np.append(a,s)
    s+=1
print(a)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45.
 46. 47. 48. 49.]


In [9]:
# 9. Развернуть вектор (первый становится последним)
print(a[::-1])

[49. 48. 47. 46. 45. 44. 43. 42. 41. 40. 39. 38. 37. 36. 35. 34. 33. 32.
 31. 30. 29. 28. 27. 26. 25. 24. 23. 22. 21. 20. 19. 18. 17. 16. 15. 14.
 13. 12. 11. 10.]


In [10]:
# 10. Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8
m=np.arange(9).reshape(3,3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
# 11. Найти индексы ненулевых элементов в [1,2,0,0,4,0]
a=np.array([1,2,0,0,4,0])
for i in range(len(a)):
    if a[i]!=0:
        print(i)

0
1
4


In [12]:
# 12. Создать 3x3 единичную матрицу
m=np.zeros(9).reshape(3,3)
print(m)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
import random

In [14]:
# 13. Создать массив 3x3x3 со случайными значениями
print(np.random.random((3,3,3)))

[[[0.1432804  0.69656408 0.60250748]
  [0.50683336 0.78169485 0.77144554]
  [0.4962712  0.96274219 0.42976436]]

 [[0.55759015 0.87137901 0.14502051]
  [0.50038487 0.98894151 0.23942016]
  [0.36931179 0.65259844 0.81087322]]

 [[0.13272939 0.86589276 0.31997024]
  [0.33327594 0.22462917 0.68294729]
  [0.39442619 0.3376553  0.48253197]]]


In [15]:
# 14. Создать массив 10x10 со случайными значениями, найти минимум и максимум
z=np.random.random((10,10))
print(np.max(z),np.min(z))

0.989813808784163 0.0018301460078267162


In [16]:
# 15. Создать случайный вектор размера 30 и найти среднее значение всех элементов
z1=np.random.random((30))
print(np.mean(z1))

0.454883668169801


In [17]:
# 16. Создать матрицу с 0 внутри, и 1 на границах
m=np.ones((3,3))
m[1,1]=0
print(m)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [18]:
# 18. Выяснить результат следующих выражений
Z = np.diag(np.arange(1, 5), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [19]:
# 19.Создать 8x8 матрицу и заполнить её в шахматном порядке
Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [20]:
# 20. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [21]:
# 21. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [22]:
# 22. Перемножить матрицы 5x3 и 3x2
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [54]:
# 23. Дан массив, поменять знак у элементов, значения которых между 3 и 8
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

In [24]:
# 24. Создать 5x5 матрицу со значениями в строках от 0 до 4
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [25]:
# 25. Есть генератор, сделать с его помощью массив
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [26]:
# 26. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое
Z = np.linspace(0,1,12)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [27]:
# 27. Отсортировать вектор
Z = np.random.random(10)
Z.sort()
print(Z)

[0.24128252 0.24540042 0.264258   0.28703205 0.43666418 0.70805898
 0.80078783 0.88073317 0.94482346 0.97802431]


In [28]:
# 28. Проверить, одинаковы ли 2 numpy массива
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


In [29]:
# 29. Сделать массив неизменяемым
Z = np.zeros(10)
Z.flags.writeable = False

In [30]:
# 30. Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.hypot(X, Y)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.77721858 0.96963992 0.53570122 1.0186892  0.7184127  0.6176098
 1.16172987 1.29327688 0.17822455 1.11431591]
[0.22362918 1.51834054 0.52921444 0.9196997  1.22575077 0.30978125
 1.00387178 0.76620025 1.08572285 0.63523815]


In [31]:
# 31. Заменить максимальный элемент на ноль
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.64097589 0.88487566 0.84349214 0.07683871 0.71562429 0.
 0.39371878 0.89551525 0.83665202 0.43109069]


In [32]:
# 32. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

In [33]:
# 33. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


In [34]:
# 34. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [35]:
# 35. Напечатать все значения в массиве
array = [1, 2, 3, 4, 5]
for value in array:
    print(value)

1
2
3
4
5


In [36]:
# 36. Найти ближайшее к заданному значению число в заданном массиве
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

96


In [37]:
# 37. Создать структурированный массив, представляющий координату (x,y) и цвет (r,g,b)
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\student\AppData\Local\Temp\ipykernel_5308\258053811.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


In [38]:
import scipy.spatial
# 38. Дан массив (100,2) координат, найти расстояние от каждой точки до каждой
Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.07032575 1.00433857 0.63572293 0.03346583 0.42333581
  0.72620285 0.47965013 0.63584405 0.01011693]
 [0.07032575 0.         1.03085264 0.60044752 0.1030886  0.42319002
  0.77749448 0.52892874 0.68814669 0.0757073 ]
 [1.00433857 1.03085264 0.         0.80482489 1.00138017 0.64684602
  0.45871644 0.58382325 0.51170248 1.01100315]
 [0.63572293 0.60044752 0.80482489 0.         0.6606568  0.32883029
  0.85862124 0.68607451 0.80761924 0.64581338]
 [0.03346583 0.1030886  1.00138017 0.6606568  0.         0.43547033
  0.70970806 0.46526294 0.61891769 0.02757902]
 [0.42333581 0.42319002 0.64684602 0.32883029 0.43547033 0.
  0.55688771 0.35978304 0.49362638 0.43260991]
 [0.72620285 0.77749448 0.45871644 0.85862124 0.70970806 0.55688771
  0.         0.24903476 0.09114474 0.72911134]
 [0.47965013 0.52892874 0.58382325 0.68607451 0.46526294 0.35978304
  0.24903476 0.         0.16187778 0.48315952]
 [0.63584405 0.68814669 0.51170248 0.80761924 0.61891769 0.49362638
  0.09114474 0.16187

In [58]:
# 39. Преобразовать массив из float в int
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(type(Z[0]))

<class 'numpy.int32'>


In [40]:
# 41. Каков эквивалент функции enumerate для numpy массивов?
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [41]:
# 42. Сформировать 2D массив с распределением Гаусса
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.hypot(X, Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D - mu) ** 2 / (2.0 * sigma ** 2)))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [59]:
# 43. Случайно расположить p элементов в 2D массив
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False), 1)
Z

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [60]:
# 44. Отнять среднее из каждой строки в матрице
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
X

array([[0.8027667 , 0.04052916, 0.5200059 , 0.58699483, 0.5248738 ,
        0.34967771, 0.30852255, 0.87183209, 0.1222994 , 0.90358885],
       [0.38703562, 0.37204536, 0.82132705, 0.21227814, 0.6679145 ,
        0.25673451, 0.13536858, 0.31040555, 0.63255382, 0.89863324],
       [0.97781897, 0.87298453, 0.93580367, 0.27729096, 0.16265318,
        0.90177548, 0.71045074, 0.67851725, 0.14689057, 0.75441079],
       [0.82063923, 0.84242219, 0.03423282, 0.97330291, 0.55715412,
        0.05160062, 0.57765955, 0.65167594, 0.0585535 , 0.1692548 ],
       [0.85608889, 0.9086525 , 0.27707757, 0.94624049, 0.02377787,
        0.31291063, 0.4120224 , 0.16190987, 0.00785111, 0.41874057]])

In [44]:
# 45. Отсортировать матрицу по n-ому столбцу
Z = np.random.randint(0,10,(3,3))
n = 1  # Нумерация с нуля
print(Z)
print(Z[Z[:,n].argsort()])

[[2 5 7]
 [8 4 5]
 [5 4 7]]
[[8 4 5]
 [5 4 7]
 [2 5 7]]


In [45]:
# 46. Определить, есть ли в 2D массиве нулевые столбцы
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


In [46]:
# 47. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 3. 3. 4. 1. 5. 3. 5. 1. 3.]


In [47]:
# 48. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов
w,h = 16,16
I = np.random.randint(0, 2, (h,w,3)).astype(np.ubyte)
F = I[...,0] * 256 * 256 + I[...,1] * 256 + I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


In [48]:
# 49. Дан четырехмерный массив, посчитать сумму по последним двум осям
A = np.random.randint(0,10, (3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[68 47 49 55]
 [47 47 69 58]
 [50 54 52 47]]


In [66]:
# 50. Найти диагональные элементы произведения матриц
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
product = np.dot(A, B)
diagonal = np.diag(product)
print(diagonal)

[ 58 154]


In [51]:
# 51. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [67]:
# 52. Поменять 2 строки в матрице
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [68]:
# 53. Рассмотрим набор из 10 троек, описывающих 10 треугольников (с общими вершинами), найти множество уникальных отрезков, составляющих все треугольники
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 10) ( 0, 31) ( 0, 53) ( 0, 57) ( 1, 37) ( 1, 43) ( 4, 21) ( 4, 61)
 ( 4, 73) ( 4, 96) ( 9, 40) ( 9, 74) (10, 57) (16, 48) (16, 79) (17, 20)
 (17, 43) (17, 44) (17, 88) (20, 43) (21, 61) (23, 58) (23, 80) (31, 53)
 (37, 43) (40, 74) (44, 88) (48, 79) (58, 80) (73, 96)]


In [69]:
# 54. Дан массив C; создать массив A, что np.bincount(A) == C
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [74]:
# 55. Посчитать среднее, используя плавающее окно
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

print(moving_average(np.arange(20), 3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [75]:
from numpy.lib import stride_tricks
# 56. Дан вектор Z, построить матрицу, первая строка которой (Z[0],Z[1],Z[2]), каждая последующая сдвинута на 1 (последняя (Z[-3],Z[-2],Z[-1]))
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [80]:
# 57. Инвертировать булево значение, или поменять знак у числового массива без создания нового
Z = np.random.uniform(-1.0,1.0,100)
Z

array([-0.89651819,  0.54109612,  0.3008903 ,  0.31065082,  0.51417643,
        0.4884935 , -0.74865353,  0.02951215,  0.23293853,  0.52242754,
        0.08427778, -0.79474286, -0.296172  ,  0.88454094,  0.95836876,
       -0.11160906, -0.84325679,  0.09770565,  0.0690489 ,  0.95127313,
       -0.29881901, -0.82366017, -0.54190456, -0.40513076, -0.72919767,
        0.86412564,  0.91336685, -0.44539401,  0.15618431,  0.54110657,
       -0.60743199, -0.2302413 , -0.60527442, -0.58783402,  0.1789601 ,
       -0.45133985,  0.80948489, -0.86108112,  0.73664725, -0.50046517,
        0.66823653, -0.25709263,  0.60389603, -0.76347974,  0.46187113,
       -0.97366072, -0.74379785, -0.91297023, -0.63878194, -0.80367534,
       -0.05580653, -0.06408925,  0.88990784,  0.74742514,  0.27466073,
       -0.01058365,  0.33132624,  0.57608251,  0.82401328,  0.46558078,
       -0.77526034,  0.53648411, -0.25790712, -0.65316163, -0.12776747,
       -0.0409282 , -0.93618955, -0.92979206,  0.61481695,  0.59

In [81]:
# 58. Рассмотрим 2 набора точек P0, P1 описания линии (2D) и точку р, как вычислить расстояние от р до каждой линии i (P0[i],P1[i])
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0] - p[...,0]) * T[:,0] + (P0[:,1] - p[...,1]) * T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U * T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 9.34933228  8.43927589 15.57170332  7.339867    7.99001126 12.56411704
  4.59405943 12.9599845  10.76225006  5.26041265]


In [83]:
# 59. Дан массив. Написать функцию, выделяющую часть массива фиксированного размера с центром в данном элементе (дополненное значением fill если необходимо)
Z = np.random.randint(0,10, (10,10))
shape = (5,5)
fill  = 0
position = (1,1)
R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)
R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P - Rs//2)
Z_stop  = (P + Rs//2)+Rs%2
R_start = (R_start - np.minimum(Z_start, 0)).tolist()
Z_start = (np.maximum(Z_start, 0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()
r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
print(Z)
print(R)

[[2 0 0 4 5 1 8 2 2 0]
 [3 1 7 1 2 1 2 6 2 5]
 [0 2 0 5 6 9 1 9 4 8]
 [7 8 1 5 8 1 4 6 3 8]
 [8 6 9 8 5 2 7 0 2 7]
 [0 4 8 3 7 8 2 2 0 0]
 [4 2 8 1 9 9 2 4 1 1]
 [5 6 2 9 4 7 5 2 7 7]
 [5 6 2 8 1 9 1 9 5 3]
 [8 7 8 9 2 8 4 4 3 5]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [85]:
# 60. Посчитать ранг матрицы
Z = np.random.uniform(0,1,(10,10))
rank = np.linalg.matrix_rank(Z)
print(rank)

10


In [86]:
# 61. Найти наиболее частое значение в массиве
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

5


In [87]:
# 62. Извлечь все смежные 3x3 блоки из 10x10 матрицы
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0] - n)
j = 1 + (Z.shape[1] - n)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 0 4]
   [2 2 1]
   [1 1 2]]

  [[0 4 3]
   [2 1 4]
   [1 2 2]]

  [[4 3 3]
   [1 4 1]
   [2 2 1]]

  [[3 3 0]
   [4 1 0]
   [2 1 2]]

  [[3 0 1]
   [1 0 2]
   [1 2 2]]

  [[0 1 0]
   [0 2 2]
   [2 2 1]]

  [[1 0 2]
   [2 2 2]
   [2 1 1]]

  [[0 2 2]
   [2 2 0]
   [1 1 2]]]


 [[[2 2 1]
   [1 1 2]
   [3 0 3]]

  [[2 1 4]
   [1 2 2]
   [0 3 2]]

  [[1 4 1]
   [2 2 1]
   [3 2 4]]

  [[4 1 0]
   [2 1 2]
   [2 4 0]]

  [[1 0 2]
   [1 2 2]
   [4 0 0]]

  [[0 2 2]
   [2 2 1]
   [0 0 1]]

  [[2 2 2]
   [2 1 1]
   [0 1 3]]

  [[2 2 0]
   [1 1 2]
   [1 3 0]]]


 [[[1 1 2]
   [3 0 3]
   [4 1 0]]

  [[1 2 2]
   [0 3 2]
   [1 0 2]]

  [[2 2 1]
   [3 2 4]
   [0 2 3]]

  [[2 1 2]
   [2 4 0]
   [2 3 0]]

  [[1 2 2]
   [4 0 0]
   [3 0 3]]

  [[2 2 1]
   [0 0 1]
   [0 3 2]]

  [[2 1 1]
   [0 1 3]
   [3 2 0]]

  [[1 1 2]
   [1 3 0]
   [2 0 4]]]


 [[[3 0 3]
   [4 1 0]
   [4 2 2]]

  [[0 3 2]
   [1 0 2]
   [2 2 1]]

  [[3 2 4]
   [0 2 3]
   [2 1 3]]

  [[2 4 0]
   [2 3 0]
   [1 3 0]]

  [[4 0 0]
   

In [95]:
# 63. Создать подкласс симметричных 2D массивов (Z[i,j] == Z[j,i])
class Masik(np.ndarray):
    def __setitem__(self, value):
        super(Masik, self).__setitem__(value)
        super(Masik, self).__setitem__( value)
def masik(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Masik)
S = masik(np.random.randint(0,10,(5,5)))
S = 42
print(S)

42


In [96]:
# 64. Рассмотрим множество матриц (n,n) и множество из p векторов (n,1). Посчитать сумму p произведений матриц (результат имеет размерность (n,1))
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [98]:
# 65. Дан массив 16x16, посчитать сумму по блокам 4x4
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
S

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

In [99]:
# 66. Написать игру "жизнь"
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N == 3) & (Z[1:-1,1:-1]==0)
    survive = ((N == 2) | (N == 3)) & (Z[1:-1,1:-1] == 1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100):
    print(Z)
    Z = iterate(Z)

[[0 0 1 ... 0 1 1]
 [0 1 0 ... 1 1 0]
 [0 1 1 ... 0 0 0]
 ...
 [0 0 1 ... 1 0 1]
 [1 0 1 ... 0 1 0]
 [1 0 0 ... 0 1 0]]
[[0 0 0 ... 0 0 0]
 [0 1 0 ... 1 1 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 1 1 0]
 [0 0 1 ... 0 1 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [

In [100]:
# 67. Найти n наибольших значений в массиве
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argpartition(-Z,n)[:n]])

[9998 9999 9997 9995 9996]


In [101]:
# 68. Построить прямое произведение массивов (все комбинации с каждым элементом)
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [102]:
# 69. Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[1 2 4 7]


In [103]:
# 70. Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3])
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[4 2 1]
 [0 4 1]
 [2 2 4]
 [1 0 2]
 [1 4 1]
 [2 3 0]
 [4 2 4]
 [3 2 4]
 [2 3 4]
 [3 0 2]]
[[4 2 1]
 [0 4 1]
 [2 2 4]
 [1 0 2]
 [1 4 1]
 [2 3 0]
 [4 2 4]
 [3 2 4]
 [2 3 4]
 [3 0 2]]


In [104]:
# 71. Преобразовать вектор чисел в матрицу бинарных представлений
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [105]:
# 72. Дан двумерный массив. Найти все различные строки
Z = np.random.randint(0, 2, (6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]]


In [112]:
# 73. Даны векторы A и B, написать einsum эквиваленты функций inner, outer, sum и mul
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
result_inner = np.einsum('i,i->', A, B)
result_outer = np.einsum('i,j->ij', A, B)
result_sum = np.einsum('i', A)
result_mul = np.einsum('i,i->i', A, B)